name: Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches:
      - dev  # Cambia 'main' por la rama que deseas monitorear
  pull_request:
    branches:
      - main  # Cambia 'main' por la rama que deseas monitorear

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      FIREBASE_WEB_API_KEY: ${{ secrets.FIREBASE_WEB_API_KEY }}
      FIREBASE_WEB_AUTH_DOMAIN: ${{ secrets.FIREBASE_WEB_AUTH_DOMAIN }}
      FIREBASE_WEB_PROJECT_ID: ${{ secrets.FIREBASE_WEB_PROJECT_ID }}
      FIREBASE_WEB_STORAGE_BUCKET: ${{ secrets.FIREBASE_WEB_STORAGE_BUCKET }}
      FIREBASE_WEB_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_WEB_MESSAGING_SENDER_ID }}
      FIREBASE_WEB_APP_ID: ${{ secrets.FIREBASE_WEB_APP_ID }}
      FIREBASE_WEB_MEASUREMENT_ID: ${{ secrets.FIREBASE_WEB_MEASUREMENT_ID }}

    steps:
      # 1. Checkout el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Instalar Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'
          cache: true
      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      # 3. Instalar dependencias
      - name: Install dependencies
        run: flutter pub get

      # 4. Construir el proyecto para web
      - name: Build Flutter Web
        # run: flutter build web --dart-define=ENV=staging
        run: >
          flutter build web -t lib/main_erp.dart --release
          --dart-define=ENV=staging
          --dart-define=FIREBASE_WEB_API_KEY=$FIREBASE_WEB_API_KEY
          --dart-define=FIREBASE_WEB_AUTH_DOMAIN=$FIREBASE_WEB_AUTH_DOMAIN
          --dart-define=FIREBASE_WEB_PROJECT_ID=$FIREBASE_WEB_PROJECT_ID
          --dart-define=FIREBASE_WEB_STORAGE_BUCKET=$FIREBASE_WEB_STORAGE_BUCKET
          --dart-define=FIREBASE_WEB_MESSAGING_SENDER_ID=$FIREBASE_WEB_MESSAGING_SENDER_ID
          --dart-define=FIREBASE_WEB_APP_ID=$FIREBASE_WEB_APP_ID
          --dart-define=FIREBASE_WEB_MEASUREMENT_ID=$FIREBASE_WEB_MEASUREMENT_ID

      # 5. Instalar Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 7. Desplegar en Firebase Hosting Preview
      - name: Deploy Preview to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_PROD }}
        run: firebase hosting:channel:deploy preview-$GITHUB_HEAD_REF --project devpto-dev --expires 7d
